# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditForm(object):
    def setupUi(self, EditForm):
        EditForm.setObjectName("EditForm")
        EditForm.resize(753, 768)
        self.label = QtWidgets.QLabel(EditForm)
        self.label.setGeometry(QtCore.QRect(200, 120, 54, 16))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(EditForm)
        self.comboBox.setGeometry(QtCore.QRect(290, 120, 74, 20))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(EditForm)
        self.label_2.setGeometry(QtCore.QRect(200, 80, 48, 16))
        self.label_2.setObjectName("label_2")
        self.label_seq = QtWidgets.QLabel(EditForm)
        self.label_seq.setGeometry(QtCore.QRect(290, 80, 54, 16))
        self.label_seq.setObjectName("label_seq")
        self.label_4 = QtWidgets.QLabel(EditForm)
        self.label_4.setGeometry(QtCore.QRect(200, 170, 36, 16))
        self.label_4.setObjectName("label_4")
        self.textEdit = QtWidgets.QTextEdit(EditForm)
        self.textEdit.setGeometry(QtCore.QRect(190, 200, 391, 201))
        self.textEdit.setObjectName("textEdit")
        self.radioButton = QtWidgets.QRadioButton(EditForm)
        self.radioButton.setGeometry(QtCore.QRect(190, 430, 41, 16))
        self.radioButton.setObjectName("radioButton")
        self.lineEdit = QtWidgets.QLineEdit(EditForm)
        self.lineEdit.setGeometry(QtCore.QRect(260, 430, 133, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_position = QtWidgets.QPushButton(EditForm)
        self.pushButton_position.setGeometry(QtCore.QRect(410, 430, 75, 23))
        self.pushButton_position.setObjectName("pushButton_position")
        self.pushButton_generate = QtWidgets.QPushButton(EditForm)
        self.pushButton_generate.setGeometry(QtCore.QRect(500, 430, 75, 23))
        self.pushButton_generate.setObjectName("pushButton_generate")
        self.label_5 = QtWidgets.QLabel(EditForm)
        self.label_5.setGeometry(QtCore.QRect(196, 490, 48, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(EditForm)
        self.label_6.setGeometry(QtCore.QRect(430, 490, 48, 16))
        self.label_6.setObjectName("label_6")
        self.toolButton_file = QtWidgets.QToolButton(EditForm)
        self.toolButton_file.setGeometry(QtCore.QRect(260, 490, 37, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_file.sizePolicy().hasHeightForWidth())
        self.toolButton_file.setSizePolicy(sizePolicy)
        self.toolButton_file.setObjectName("toolButton_file")
        self.toolButton_img = QtWidgets.QToolButton(EditForm)
        self.toolButton_img.setGeometry(QtCore.QRect(490, 490, 37, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_img.sizePolicy().hasHeightForWidth())
        self.toolButton_img.setSizePolicy(sizePolicy)
        self.toolButton_img.setObjectName("toolButton_img")
        self.pushButton_cancel = QtWidgets.QPushButton(EditForm)
        self.pushButton_cancel.setGeometry(QtCore.QRect(380, 580, 75, 23))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.pushButton_submit = QtWidgets.QPushButton(EditForm)
        self.pushButton_submit.setGeometry(QtCore.QRect(480, 580, 75, 23))
        self.pushButton_submit.setObjectName("pushButton_submit")

        self.retranslateUi(EditForm)
        self.pushButton_cancel.clicked.connect(EditForm.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(EditForm)

    def retranslateUi(self, EditForm):
        _translate = QtCore.QCoreApplication.translate
        EditForm.setWindowTitle(_translate("EditForm", "Form"))
        self.label.setText(_translate("EditForm", "消息类型:"))
        self.comboBox.setItemText(0, _translate("EditForm", "None"))
        self.comboBox.setItemText(1, _translate("EditForm", "探测信息"))
        self.comboBox.setItemText(2, _translate("EditForm", "指令信息"))
        self.comboBox.setItemText(3, _translate("EditForm", "回复信息"))
        self.label_2.setText(_translate("EditForm", "序列号："))
        self.label_seq.setText(_translate("EditForm", "TextLabel"))
        self.label_4.setText(_translate("EditForm", "描述："))
        self.radioButton.setText(_translate("EditForm", "GPS"))
        self.pushButton_position.setText(_translate("EditForm", "定位"))
        self.pushButton_generate.setText(_translate("EditForm", "生成"))
        self.label_5.setText(_translate("EditForm", "添加文件"))
        self.label_6.setText(_translate("EditForm", "添加图像"))
        self.toolButton_file.setText(_translate("EditForm", "..."))
        self.toolButton_img.setText(_translate("EditForm", "..."))
        self.pushButton_cancel.setText(_translate("EditForm", "取消"))
        self.pushButton_submit.setText(_translate("EditForm", "确定"))
