# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/dell/workspace/UI/ui/edit.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditForm(object):
    def setupUi(self, EditForm):
        EditForm.setObjectName("EditForm")
        EditForm.resize(807, 687)
        self.widget = QtWidgets.QWidget(EditForm)
        self.widget.setGeometry(QtCore.QRect(120, 30, 551, 591))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(80)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_seq = QtWidgets.QLabel(self.widget)
        self.label_seq.setObjectName("label_seq")
        self.horizontalLayout.addWidget(self.label_seq)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton = QtWidgets.QRadioButton(self.widget)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_3.addWidget(self.radioButton)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.pushButton_position = QtWidgets.QPushButton(self.widget)
        self.pushButton_position.setObjectName("pushButton_position")
        self.horizontalLayout_3.addWidget(self.pushButton_position)
        self.pushButton_generate = QtWidgets.QPushButton(self.widget)
        self.pushButton_generate.setObjectName("pushButton_generate")
        self.horizontalLayout_3.addWidget(self.pushButton_generate)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.toolButton_img = QtWidgets.QToolButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_img.sizePolicy().hasHeightForWidth())
        self.toolButton_img.setSizePolicy(sizePolicy)
        self.toolButton_img.setObjectName("toolButton_img")
        self.horizontalLayout_4.addWidget(self.toolButton_img)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.toolButton_file = QtWidgets.QToolButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_file.sizePolicy().hasHeightForWidth())
        self.toolButton_file.setSizePolicy(sizePolicy)
        self.toolButton_file.setObjectName("toolButton_file")
        self.horizontalLayout_4.addWidget(self.toolButton_file)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.listWidget_images = QtWidgets.QListWidget(self.widget)
        self.listWidget_images.setObjectName("listWidget_images")
        self.verticalLayout_2.addWidget(self.listWidget_images)
        self.listWidget_files = QtWidgets.QListWidget(self.widget)
        self.listWidget_files.setObjectName("listWidget_files")
        self.verticalLayout_2.addWidget(self.listWidget_files)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.pushButton_cancel = QtWidgets.QPushButton(self.widget)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_5.addWidget(self.pushButton_cancel)
        self.pushButton_submit = QtWidgets.QPushButton(self.widget)
        self.pushButton_submit.setObjectName("pushButton_submit")
        self.horizontalLayout_5.addWidget(self.pushButton_submit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)

        self.retranslateUi(EditForm)
        self.pushButton_cancel.clicked.connect(EditForm.close)
        QtCore.QMetaObject.connectSlotsByName(EditForm)

    def retranslateUi(self, EditForm):
        _translate = QtCore.QCoreApplication.translate
        EditForm.setWindowTitle(_translate("EditForm", "Form"))
        self.label_2.setText(_translate("EditForm", "序列号："))
        self.label_seq.setText(_translate("EditForm", "TextLabel"))
        self.label.setText(_translate("EditForm", "消息类型:"))
        self.comboBox.setItemText(0, _translate("EditForm", "None"))
        self.comboBox.setItemText(1, _translate("EditForm", "探测信息"))
        self.comboBox.setItemText(2, _translate("EditForm", "指令信息"))
        self.comboBox.setItemText(3, _translate("EditForm", "回复信息"))
        self.label_4.setText(_translate("EditForm", "描述："))
        self.radioButton.setText(_translate("EditForm", "GPS"))
        self.pushButton_position.setText(_translate("EditForm", "定位"))
        self.pushButton_generate.setText(_translate("EditForm", "生成"))
        self.label_6.setText(_translate("EditForm", "添加图像:"))
        self.toolButton_img.setText(_translate("EditForm", "..."))
        self.label_5.setText(_translate("EditForm", "添加文件:"))
        self.toolButton_file.setText(_translate("EditForm", "..."))
        self.pushButton_cancel.setText(_translate("EditForm", "取消"))
        self.pushButton_submit.setText(_translate("EditForm", "确定"))


import resouce_rc
